[package]
name = "codec2"
version = "0.2.0"
edition = "2021"

[dependencies]
walkdir = "2.5.0"
rayon = "1.10.0"
clap = { version = "4.5.26", features = ["derive"] }
log = "0.4.25"
env_logger = "0.11.6"